name: Airsoft
favicon: null
layout_spectrum: 0.19055
typography_spectrum: 0.64209
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#49494a'
    - '#222322'
    - '#333333'
    - '#000000'
    - '#555555'
  brandStrength: 0
  lightness: 0.563284152885899
  saturation: 0
  rhythmicContrast: 0.768885153811425
purpose: []
