name: Airsoft
favicon: null
layout_spectrum: 0.32781680719926953
typography_spectrum: 0.1544260720256716
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7887886958196759
  lightness: 0.563284152885899
  saturation: 0.0024558203294873238
  rhythmicContrast: 0.768885153811425
purpose: []
